<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Collaberas-MacBook-Pro.local" failures="15" tests="15" name="Android Phone Test" time="67.249" errors="0" timestamp="2023-05-13T01:32:54 PST">
  <testcase classname="tests_AndroidPhone.TC_BAA_01" name="launchApp" time="0.019">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.relevantcodes.extentreports.ExtentTest.log(com.relevantcodes.extentreports.LogStatus, String)&amp;quot; because &amp;quot;this.test&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.relevantcodes.extentreports.ExtentTest.log(com.relevantcodes.extentreports.LogStatus, String)" because "this.test" is null
at tests_AndroidPhone.TC_BAA_01.launchApp(TC_BAA_01.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- launchApp -->
  <testcase classname="tests_AndroidPhone.TC_BAA_01" name="createAccount" time="8.791">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests_AndroidPhone.TC_BAA_01.createAccount(TC_BAA_01.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- createAccount -->
  <testcase classname="tests_AndroidPhone.TC_BAA_01" name="login" time="4.066">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests_AndroidPhone.TC_BAA_01.login(TC_BAA_01.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="tests_AndroidPhone.TC_BAA_01" name="validateEnterDetails" time="1.635">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.relevantcodes.extentreports.ExtentTest.log(com.relevantcodes.extentreports.LogStatus, String)&amp;quot; because &amp;quot;this.test&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.relevantcodes.extentreports.ExtentTest.log(com.relevantcodes.extentreports.LogStatus, String)" because "this.test" is null
at tests_AndroidPhone.TC_BAA_01.validateEnterDetails(TC_BAA_01.java:100)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- validateEnterDetails -->
  <testcase classname="tests_AndroidPhone.TC_BAA_02" name="launchApp" time="0.003">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.relevantcodes.extentreports.ExtentTest.log(com.relevantcodes.extentreports.LogStatus, String)&amp;quot; because &amp;quot;this.test&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.relevantcodes.extentreports.ExtentTest.log(com.relevantcodes.extentreports.LogStatus, String)" because "this.test" is null
at tests_AndroidPhone.TC_BAA_02.launchApp(TC_BAA_02.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- launchApp -->
  <testcase classname="tests_AndroidPhone.TC_BAA_02" name="login" time="3.197">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests_AndroidPhone.TC_BAA_02.login(TC_BAA_02.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="tests_AndroidPhone.TC_BAA_02" name="addTransaction" time="3.32">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests_AndroidPhone.TC_BAA_02.addTransaction(TC_BAA_02.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- addTransaction -->
  <testcase classname="tests_AndroidPhone.TC_BAA_02" name="viewTransaction" time="1.164">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.relevantcodes.extentreports.ExtentTest.log(com.relevantcodes.extentreports.LogStatus, String)&amp;quot; because &amp;quot;this.test&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.relevantcodes.extentreports.ExtentTest.log(com.relevantcodes.extentreports.LogStatus, String)" because "this.test" is null
at tests_AndroidPhone.TC_BAA_02.viewTransaction(TC_BAA_02.java:81)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- viewTransaction -->
  <testcase classname="tests_AndroidPhone.TC_BAA_02" name="validateTransaction" time="1.103">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests_AndroidPhone.TC_BAA_02.validateTransaction(TC_BAA_02.java:99)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- validateTransaction -->
  <testcase classname="tests_AndroidPhone.TC_BAA_03" name="launchApp" time="0.004">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.relevantcodes.extentreports.ExtentTest.log(com.relevantcodes.extentreports.LogStatus, String)&amp;quot; because &amp;quot;this.test&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.relevantcodes.extentreports.ExtentTest.log(com.relevantcodes.extentreports.LogStatus, String)" because "this.test" is null
at tests_AndroidPhone.TC_BAA_03.launchApp(TC_BAA_03.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- launchApp -->
  <testcase classname="tests_AndroidPhone.TC_BAA_03" name="createAccount" time="7.009">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests_AndroidPhone.TC_BAA_03.createAccount(TC_BAA_03.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- createAccount -->
  <testcase classname="tests_AndroidPhone.TC_BAA_03" name="login" time="2.942">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests_AndroidPhone.TC_BAA_03.login(TC_BAA_03.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="tests_AndroidPhone.TC_BAA_03" name="addTransaction" time="4.348">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests_AndroidPhone.TC_BAA_03.addTransaction(TC_BAA_03.java:88)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- addTransaction -->
  <testcase classname="tests_AndroidPhone.TC_BAA_03" name="viewTransaction" time="2.203">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.relevantcodes.extentreports.ExtentTest.log(com.relevantcodes.extentreports.LogStatus, String)&amp;quot; because &amp;quot;this.test&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.relevantcodes.extentreports.ExtentTest.log(com.relevantcodes.extentreports.LogStatus, String)" because "this.test" is null
at tests_AndroidPhone.TC_BAA_03.viewTransaction(TC_BAA_03.java:102)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- viewTransaction -->
  <testcase classname="tests_AndroidPhone.TC_BAA_03" name="validateTransaction" time="0.118">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests_AndroidPhone.TC_BAA_03.validateTransaction(TC_BAA_03.java:120)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- validateTransaction -->
</testsuite> <!-- Android Phone Test -->
