<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Collaberas-MacBook-Pro.local" failures="1" tests="16" name="tests.TestIOS" time="78.705" errors="0" timestamp="2023-05-17T20:29:25 PST" skipped="0">
  <testcase classname="tests.TestIOS" name="UI_01" time="3.656"/>
  <system-out/>
  <testcase classname="tests.TestIOS" name="UI_02" time="1.572"/>
  <system-out/>
  <testcase classname="tests.TestIOS" name="UI_03" time="3.790">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at tests.TestIOS.UI_03(TestIOS.java:86)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- UI_03 -->
  <system-out/>
  <testcase classname="tests.TestIOS" name="UI_04" time="6.387"/>
  <system-out/>
  <testcase classname="tests.TestIOS" name="UI_05" time="2.845"/>
  <system-out/>
  <testcase classname="tests.TestIOS" name="UI_06" time="3.259"/>
  <system-out/>
  <testcase classname="tests.TestIOS" name="UI_07" time="12.259"/>
  <system-out/>
  <testcase classname="tests.TestIOS" name="UI_08" time="9.120"/>
  <system-out/>
  <testcase classname="tests.TestIOS" name="UI_09" time="4.947"/>
  <system-out/>
  <testcase classname="tests.TestIOS" name="UI_10" time="4.572"/>
  <system-out/>
  <testcase classname="tests.TestIOS" name="UI_11" time="3.685"/>
  <system-out/>
  <testcase classname="tests.TestIOS" name="UI_12" time="2.396"/>
  <system-out/>
  <testcase classname="tests.TestIOS" name="UI_13" time="7.791"/>
  <system-out/>
  <testcase classname="tests.TestIOS" name="UI_14" time="3.573"/>
  <system-out/>
  <testcase classname="tests.TestIOS" name="UI_15" time="5.014"/>
  <system-out/>
  <testcase classname="tests.TestIOS" name="UI_17" time="3.839"/>
  <system-out/>
</testsuite> <!-- tests.TestIOS -->
